spring.application.name=AuthApp

spring.datasource.url=jdbc:mysql://localhost:3306/fsads52
spring.datasource.username=root
spring.datasource.password=Aravind@17

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aravindnelavelli@gmail.com
spring.mail.password=xblu thsq syqw nmad

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true